
#MCU = atmega328
#FREWQ = 16000000

#BOARD_TAG = atmega328
BOARD_TAG = gertduino328
MONITOR_PORT = /dev/ttyACM0

ARDUINO_LIBS = SoftwareSerial AFMotor

ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = /usr/share/arduino
AVR_TOOLS_DIR = /usr

include /usr/share/arduino/Arduino.mk
